name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: VideoSplitter
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip pyinstaller

      - name: Fetch FFmpeg binaries
        shell: pwsh
        run: |
          $ffmpegDir = Join-Path $PWD "third_party\ffmpeg\win-x64"
          New-Item -ItemType Directory -Force -Path $ffmpegDir | Out-Null

          $downloadPath = Join-Path $env:RUNNER_TEMP "ffmpeg.zip"
          $extractPath = Join-Path $env:RUNNER_TEMP "ffmpeg"
          $ffmpegUri = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"

          Invoke-WebRequest -Uri $ffmpegUri -OutFile $downloadPath
          Expand-Archive -Path $downloadPath -DestinationPath $extractPath -Force

          $extractedRoot = Get-ChildItem -Path $extractPath | Where-Object { $_.PSIsContainer } | Select-Object -First 1
          if (-not $extractedRoot) {
              throw "Extracted FFmpeg package not found."
          }

          Copy-Item -Path (Join-Path $extractedRoot.FullName "bin\ffmpeg.exe") -Destination $ffmpegDir -Force
          Copy-Item -Path (Join-Path $extractedRoot.FullName "bin\ffprobe.exe") -Destination $ffmpegDir -Force

          $licenseSource = Join-Path $extractedRoot.FullName "LICENSE.txt"
          if (Test-Path $licenseSource) {
              Copy-Item -Path $licenseSource -Destination (Join-Path $ffmpegDir "LICENSE.txt") -Force
          }

      - name: Run PyInstaller
        run: pyinstaller --onefile --windowed --icon assets/icon.ico --name VideoSplitter --paths src --add-binary "third_party\ffmpeg\win-x64\ffmpeg.exe;." --add-binary "third_party\ffmpeg\win-x64\ffprobe.exe;." src/app.py

      - name: Prepare artifact
        shell: pwsh
        run: |
          $packageDir = "dist\VideoSplitter_package"
          New-Item -ItemType Directory -Force -Path $packageDir | Out-Null
          Copy-Item -Path "dist\VideoSplitter.exe" -Destination $packageDir -Force
          Copy-Item -Path "third_party\ffmpeg\win-x64\LICENSE.txt" -Destination (Join-Path $packageDir "FFmpeg_LICENSE.txt") -Force
          Copy-Item -Path "README.md" -Destination (Join-Path $packageDir "README.txt") -Force
          Compress-Archive -Path "$packageDir\*" -DestinationPath "dist\VideoSplitter-win64.zip" -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VideoSplitter-win64
          path: VideoSplitter/dist/VideoSplitter-win64.zip
